### ISSUE TITLE
Problem in deploying to self host

### ISSUE THREAD

**Issue by its-joe04** [TgCatUB/catuserbot#324]
I just tried to run CatUserBot on my Debian 11 VPS. After installing and configuring everything, when I attempted to run it using python3 -m userbot, I encountered the following error:

Traceback (most recent call last):
  File "/usr/lib/python3.7/runpy.py", line 183, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/usr/lib/python3.7/runpy.py", line 142, in _get_module_details
    return _get_module_details(pkg_main_name, error)
  File "/usr/lib/python3.7/runpy.py", line 109, in _get_module_details
    __import__(pkg_name)
  File "/root/catuserbot/userbot/__init__.py", line 8, in <module>
    from .core.logger import logging
  File "/root/catuserbot/userbot/core/__init__.py", line 1, in <module>
    from .decorators import check_owner
  File "/root/catuserbot/userbot/core/decorators.py", line 7, in <module>
    from ..sql_helper.globals import gvarstatus
  File "/root/catuserbot/userbot/sql_helper/globals.py", line 44
    if rem := (
            ^
SyntaxError: invalid syntax

note: I encountered an error while installing the requirements because of git+https://github.com/sandy1709/py-googletrans. To resolve this, I removed it from the requirements.txt file and installed all the remaining dependencies. Then, I separately installed py-googletrans using pip3 install py-googletrans.

**Comment by Jisan09** [comment]
Ya there was issue with googletrans version, it [fixed now](https://github.com/sandy1709/py-googletrans/pull/1).
